Repository SEOULMILK-1/SEOULMILK1_FE, pull requests merged in 2025-03, with the labels that each got.

#25 [✨ Feature] 관리자_홈 대시보드 UI 구현
  public/Icon/Check.tsx
  src/pages/home/DashBoard.tsx
  src/pages/home/components/DashDataTable.tsx
  src/pages/home/components/DashTableHeader.tsx
Labels: 💄 Style

#29 [✨ Feature] 달력 컴포넌트, 관리자_회원관리 페이지 표 UI 구현
  public/Icon/CalendarIcon.tsx
  public/Icon/LocationIcon.tsx
  public/Icon/PlusIcon.tsx
  src/common/Calendar.tsx
  src/common/Search.tsx
  src/common/SelectCalendar.tsx
  src/pages/ADMIN/home/DashBoard.tsx
  src/pages/ADMIN/home/components/DashDataTable.tsx
  src/pages/ADMIN/home/components/DashTableHeader.tsx
  src/pages/ADMIN/home/index.tsx
  src/pages/ADMIN/user/UserManage.tsx
  src/pages/ADMIN/user/components/UserDataTable.tsx
  src/pages/ADMIN/user/components/UserDataTableHeader.tsx
  src/pages/CompoExample.tsx
  src/pages/HQ/customer/HeadCustomer.tsx
  src/pages/HQ/tax/index.tsx
  src/routes/router.tsx
  src/utils/UserDummy.ts
  src/utils/test.tsx
Labels: 💄 Style

#30 [✨ Feature] 사이드모달, 사이드바 role 구분
  public/Icon/CheckIcon.tsx
  public/Icon/CustomerIcon.tsx
  public/Icon/EditIcon.tsx
  public/Icon/SidebarUploadIcon.tsx
  public/Icon/SpeakerGray.tsx
  public/Icon/UserIcon.tsx
  src/common/AdminSideModal.tsx
  src/common/SideModal/AdminSideModal.tsx
  src/common/SideModal/CSSideModal.tsx
  src/common/SideModal/HQSideModal.tsx
  src/common/SideModal/SideModal.tsx
  src/common/Sidebar.tsx
  src/index.css
  src/outlet/CSRootLayout.tsx
  src/outlet/HQRootLayout.tsx
  src/pages/ADMIN/user/components/UserDataTable.tsx
  src/pages/ADMIN/user/components/UserSideModal.tsx
  src/pages/CompoExample.tsx
  src/routes/SidebarRouter.tsx
  src/routes/router.tsx
  src/utils/UserDummy.ts
Labels: ✨ Feature, 💄 Style

#35 [✨ Feature] 본사&대리점 회원가입 페이지 UI
  public/Icon/CsSignupColor.tsx
  public/Icon/CsSignupGray.tsx
  public/Icon/DeleteXIcon.tsx
  public/Icon/SignupCheck.tsx
  public/Icon/SignupColor.tsx
  public/Icon/SignupGray.tsx
  src/common/AgreeModal.tsx
  src/common/ConfirmModal.tsx
  src/common/UserSideModal.tsx
  src/pages/ADMIN/home/DashBoard.tsx
  src/pages/ADMIN/home/components/DashDataTable.tsx
  src/pages/CS/cssignup/CSSignup.tsx
  src/pages/CS/cssignup/components/CsSignup1.tsx
  src/pages/CS/cssignup/components/CsSignup2.tsx
  src/pages/HQ/signup/HeadSignup.tsx
  src/pages/HQ/signup/components/CircleNumber.tsx
  src/pages/HQ/signup/components/Signup1.tsx
  src/pages/HQ/signup/components/Signup2.tsx
  src/pages/HQ/signup/components/SignupButton.tsx
  src/pages/HQ/signup/components/SignupInput.tsx
  src/pages/HQ/signup/components/SignupModal.tsx
  src/pages/HQ/signup/index.tsx
  src/pages/login/components/LoginFooter.tsx
  src/routes/router.tsx
  src/utils/UserDummy.ts
Labels: 💄 Style

#37 [🐛 Bug] 배포링크 설정
  index.html
  vercel.json
Labels: 🐛 Bug

#41 [✨ Feature] 세금계산서 업로드 UI 초기구현
  package-lock.json
  package.json
  public/Icon/Horizontal.tsx
  public/Icon/ResetIcon.tsx
  public/Icon/Rotation1.tsx
  public/Icon/Rotation2.tsx
  public/Icon/TaxUpload.svg
  public/Icon/WarningIcon.tsx
  public/Icon/홈택스.svg
  src/common/Header.tsx
  src/common/Sidebar.tsx
  src/hooks/test.tsx
  src/pages/CS/UploadTax/ImageCrop.tsx
  src/pages/CS/UploadTax/SidebarUploadBtn.tsx
  src/pages/CS/UploadTax/Step1.tsx
  src/pages/CS/UploadTax/Step2.tsx
  src/pages/CS/UploadTax/Step3.tsx
  src/pages/CS/UploadTax/StepProgress.tsx
  src/pages/CompoExample.tsx
  src/pages/index.ts
  src/pages/login/index.tsx
  src/routes/router.tsx
Labels: ✨ Feature, 💄 Style

#47 [✨ Feature] 세금계산서 업로드 UI 추가
  src/common/Header.tsx
  src/common/Sidebar.tsx
  src/pages/ADMIN/board/index.tsx
  src/pages/ADMIN/payment/index.tsx
  src/pages/ADMIN/tax/index.tsx
  src/pages/CS/UploadTax/ImageCrop.tsx
  src/pages/CS/UploadTax/Step1.tsx
  src/pages/CS/home/index.tsx
  src/routes/SidebarRouter.tsx
  src/routes/router.tsx
Labels: ✨ Feature, 💄 Style

#49 [✨ Feature] 본사_홈 UI 구현
  public/Icon/HQHome.tsx
  public/Icon/TagIcon.tsx
  src/pages/HQ/home/HQDashBoard.tsx
  src/pages/HQ/home/components/HQAgencyModal.tsx
  src/pages/HQ/home/components/WaitingChartContents.tsx
  src/pages/HQ/home/components/WaitingChartHeader.tsx
  src/pages/HQ/home/components/WaitingTax.tsx
  src/pages/HQ/home/components/WriteChartContents.tsx
  src/pages/HQ/home/components/WriteChartHeader.tsx
  src/pages/HQ/home/components/WritePayment.tsx
  src/pages/HQ/payment/components/PaymentChart.tsx
  src/pages/HQ/payment/components/PaymentContent.tsx
  src/routes/SidebarRouter.tsx
  src/routes/router.tsx
Labels: 💄 Style

#52 [✨ Feature] 회원삭제 구현
  src/pages/ADMIN/user/components/UserSideModal.tsx
Labels: ✨ Feature

#54 [✨ Feature] 로그인 / 회원가입 api 연결
  package-lock.json
  public/Icon/ToggleIcon.tsx
  src/hooks/test.tsx
  src/hooks/useCsSignupStore.ts
  src/hooks/useSignupStore.ts
  src/pages/CS/cssignup/components/CsDropDown.tsx
  src/pages/CS/cssignup/components/CsSignup1.tsx
  src/pages/CS/cssignup/components/CsSignup2.tsx
  src/pages/HQ/signup/components/Signup1.tsx
  src/pages/HQ/signup/components/Signup2.tsx
Labels: ✨ Feature

#57 [✨ Feature] 로그인 api 연결
  .gitignore
  src/pages/HQ/signup/components/Signup1.tsx
  src/pages/HQ/signup/components/Signup2.tsx
  src/pages/login/index.tsx
  src/routes/router.tsx
  tsconfig.app.json
Labels: 🔗 API

#59 [🐛 Bug] 빌드 에러 수정
  src/common/Header.tsx
  src/common/Sidebar.tsx
  src/pages/CS/UploadTax/Step1.tsx
  src/routes/router.tsx
  tsconfig.json
Labels: 🐛 Bug

#61 [🐛 Bug] mixed content 에러
  index.html
  src/routes/router.tsx
Labels: 🐛 Bug

#67 [✨ Feature] 관리자 화면 수정사항
  src/pages/ADMIN/user/components/UserDataTable.tsx
  src/pages/ADMIN/user/components/UserSideModal.tsx
Labels: 💄 Style

#78 [✨ Feature] OCR 텍스트추출, 검증
  package-lock.json
  package.json
  public/Icon/ConfirmUploadModal.svg
  src/common/Header.tsx
  src/common/Sidebar.tsx
  src/common/StatusBagde.tsx
  src/common/TaxDetailModal.tsx
  src/pages/CS/TaxUpload/ConfirmUpload.tsx
  src/pages/CS/TaxUpload/DuplicateTaxModal.tsx
  src/pages/CS/TaxUpload/ImageCrop.tsx
  src/pages/CS/TaxUpload/SidebarUploadBtn.tsx
  src/pages/CS/TaxUpload/Step1.tsx
  src/pages/CS/TaxUpload/Step2.tsx
  src/pages/CS/TaxUpload/Step3.tsx
  src/pages/CS/TaxUpload/StepProgress.tsx
  src/pages/CS/UploadTax/Step1.tsx
  src/pages/CS/tax/EditTax.tsx
  src/pages/CS/tax/components/CustomerChartContent.tsx
  src/pages/HQ/payment/Payment.tsx
  src/pages/HQ/tax/components/CustomerChartContent.tsx
  src/pages/HQ/tax/index.tsx
  src/routes/router.tsx
  src/utils/imageTest.png
Labels: ✨ Feature, 🔗 API

#79 [✨ Feature] 세금계산서 (HQ/tax) 기능 연결
  src/common/ChartPagination.tsx
  src/common/Search.tsx
  src/common/SelectCalendar.tsx
  src/common/SelectMonth.tsx
  src/common/StateDropdown.tsx
  src/common/StatusBagde.tsx
  src/common/TaxDetailModal.tsx
  src/pages/ADMIN/home/components/DashDataTable.tsx
  src/pages/ADMIN/user/components/UserDataTable.tsx
  src/pages/ADMIN/user/components/UserSideModal.tsx
  src/pages/HQ/customer/components/CustomerChart.tsx
  src/pages/HQ/customer/components/CustomerChartContent.tsx
  src/pages/HQ/tax/components/CustomerChart.tsx
  src/pages/HQ/tax/components/CustomerChartContent.tsx
  src/pages/HQ/tax/components/CustomerChartHeader.tsx
  src/pages/HQ/tax/index.tsx
Labels: ✨ Feature, 🔗 API

#80 [✨ Feature] 회원가입 중복검사 처리
  src/pages/HQ/signup/components/Signup1.tsx
Labels: ✨ Feature, 🔗 API

#85 [✨ Feature] 대리점_홈 UI 구현 및 기능연결
  src/pages/CS/home/components/Approve.tsx
  src/pages/CS/home/components/ApproveHeader.tsx
  src/pages/CS/home/components/Refuse.tsx
  src/pages/CS/home/components/RefuseHeader.tsx
  src/pages/CS/home/index.tsx
  src/pages/HQ/signup/components/SignupModal.tsx
  src/routes/SidebarRouter.tsx
  src/routes/router.tsx
Labels: 💄 Style, 🔗 API

#86 [✨ Feature] 모바일버전 UI , 업로드 플로우 구현
  package-lock.json
  package.json
  public/Icon/CompleteCheck.tsx
  src/App.tsx
  src/pages/CS/tax/components/CustomerChart.tsx
  src/pages/CS/tax/components/CustomerChartContent.tsx
  src/pages/CS/tax/index.tsx
  src/pages/HQ/payment/Payment.tsx
  src/pages/HQ/tax/components/CustomerChartContent.tsx
  src/pages/MOBILE/Home.tsx
  src/pages/MOBILE/uploadTax/Complete.tsx
  src/pages/MOBILE/uploadTax/ImageCrop.tsx
  src/pages/MOBILE/uploadTax/Step1Mobile.tsx
  src/pages/MOBILE/uploadTax/Step2Mobile.tsx
  src/pages/MOBILE/uploadTax/Step3Mobile.tsx
  src/routes/MobileRouter.tsx
  src/routes/WebRouter.tsx
Labels: ✨ Feature, 💄 Style, 🔗 API

#88 [✨ Feature] 모바일버전 중복처리, userdata store저장
  package-lock.json
  package.json
  public/Icon/ArrowIcon.tsx
  public/Icon/MobileCamera.tsx
  public/Icon/MobileUpload.tsx
  src/App.tsx
  src/common/SideModal/SideModal.tsx
  src/common/Sidebar.tsx
  src/common/StatusBagde.tsx
  src/common/TaxDetailModal.tsx
  src/common/UserSideModal.tsx
  src/index.css
  src/pages/CS/TaxUpload/DuplicateTaxModal.tsx
  src/pages/CS/TaxUpload/SidebarUploadBtn.tsx
  src/pages/CS/TaxUpload/Step1.tsx
  src/pages/CS/TaxUpload/Step3.tsx
  src/pages/CS/tax/EditTax.tsx
  src/pages/HQ/payment/Payment.tsx
  src/pages/HQ/payment/components/PaymentChart.tsx
  src/pages/HQ/payment/components/PaymentContent.tsx
  src/pages/MOBILE/Home.tsx
  src/pages/MOBILE/uploadTax/Complete.tsx
  src/pages/MOBILE/uploadTax/ImageCrop.tsx
  src/pages/MOBILE/uploadTax/Step1Mobile.tsx
  src/pages/MOBILE/uploadTax/Step3Mobile.tsx
  src/pages/login/index.tsx
  src/routes/MobileRouter.tsx
  src/store/useAuthStore.ts
Labels: ✨ Feature, 🔗 API

#89 [✨ Feature] 본사_홈 기능 연결
  .github/workflows/deploy.yml
  build.sh
  public/Icon/Loading.tsx
  public/Icon/ModalCompleteIcon.tsx
  public/Icon/TaxApproveIcon.tsx
  public/Icon/TaxRefuseIcon.tsx
  public/Icon/UnderIcon.tsx
  src/common/ChartPagination.tsx
  src/common/Search.tsx
  src/common/StateDropdown.tsx
  src/common/StatusBagde.tsx
  src/common/TaxDetailModal.tsx
  src/pages/CS/cssignup/components/CsSignup1.tsx
  src/pages/CS/cssignup/components/CsSignup2.tsx
  src/pages/CS/home/components/Approve.tsx
  src/pages/CS/home/components/Refuse.tsx
  src/pages/CS/tax/components/CustomerChart.tsx
  src/pages/CS/tax/components/CustomerChartContent.tsx
  src/pages/CS/tax/index.tsx
  src/pages/HQ/home/HQDashBoard.tsx
  src/pages/HQ/home/components/HQAgencyModal.tsx
  src/pages/HQ/home/components/WaitingChartContents.tsx
  src/pages/HQ/home/components/WaitingChartHeader.tsx
  src/pages/HQ/home/components/WaitingTax.tsx
  src/pages/HQ/home/components/WriteChartContents.tsx
  src/pages/HQ/home/components/WriteChartHeader.tsx
  src/pages/HQ/home/components/WritePayment.tsx
  src/pages/HQ/payment/Payment.tsx
  src/pages/HQ/payment/components/PaymentChart.tsx
  src/pages/HQ/payment/components/PaymentContent.tsx
  src/pages/HQ/paymentDetail/PaymentDetail.tsx
  src/pages/HQ/paymentDetail/PaymentDetailModal.tsx
  src/pages/HQ/signup/components/Signup1.tsx
  src/pages/HQ/signup/components/Signup2.tsx
  src/pages/HQ/tax/components/CustomerChartContent.tsx
  src/pages/HQ/tax/components/TaxDetailModal.tsx
  src/pages/HQ/tax/index.tsx
  src/store/useCsSignupStore.ts
  src/store/useSignupStore.ts
Labels: ✨ Feature, 💄 Style, 🔗 API

#90 [✨ Feature] 모바일 버전 추가구현
  index.html
  public/Icon/LogoRed.svg
  src/App.tsx
  src/common/SideModal/SideModal.tsx
  src/common/StatusBagde.tsx
  src/common/TaxDetailModal.tsx
  src/pages/ADMIN/user/components/UserDataTable.tsx
  src/pages/CS/TaxUpload/DuplicateTaxModal.tsx
  src/pages/CS/TaxUpload/Step1.tsx
  src/pages/CS/TaxUpload/Step2.tsx
  src/pages/CS/TaxUpload/Step3.tsx
  src/pages/CS/TaxUpload/StepProgress.tsx
  src/pages/HQ/payment/components/PaymentChartHeader.tsx
  src/pages/HQ/payment/components/PaymentContent.tsx
  src/pages/HQ/paymentDetail/AccountEditModal.tsx
  src/pages/HQ/paymentDetail/PaymentDetail.tsx
  src/pages/MOBILE/EditTaxMobile.tsx
  src/pages/MOBILE/Home.tsx
  src/pages/MOBILE/TaxDetail.tsx
  src/pages/MOBILE/TaxMobile.tsx
  src/pages/MOBILE/uploadTax/Step3Mobile.tsx
  src/pages/login/index.tsx
  src/routes/MobileRouter.tsx
  src/store/useAuthStore.ts
  tailwind.config.ts
  vite.config.ts
Labels: ✨ Feature, 💄 Style, 🔗 API

#97 [🐛 Bug] ocr 에러 모달, hq/tax 상세조회페이지
  src/common/ConfirmModal.tsx
  src/pages/CS/TaxUpload/ConfirmUpload.tsx
  src/pages/CS/TaxUpload/Step1.tsx
  src/pages/HQ/tax/components/CustomerChartContent.tsx
  src/pages/HQ/tax/components/TaxDetailModal.tsx
Labels: 🐛 Bug, 💄 Style

#98 [🐛 Bug] QA관련 수정사항
  src/pages/ADMIN/board/index.tsx
  src/pages/ADMIN/payment/components/AdminPaymentChartContent.tsx
  src/pages/ADMIN/paymentDetail/AdminPaymentDetail.tsx
  src/pages/ADMIN/paymentDetail/AdminPaymentDetailModal.tsx
  src/pages/ADMIN/paymentDetail/components/PaymentInfo.tsx
  src/pages/ADMIN/paymentDetail/components/TaxInvoiceItem.tsx
  src/pages/ADMIN/tax/components/AdminChartContent.tsx
  src/pages/ADMIN/tax/components/AdminChartHeader.tsx
  src/pages/ADMIN/tax/components/AdminTaxDetailModal.tsx
  src/pages/ADMIN/user/components/UserDataTable.tsx
  src/pages/HQ/customer/components/CustomerChart.tsx
  src/pages/HQ/customer/components/CustomerChartContent.tsx
  src/pages/HQ/tax/components/CustomerChartContent.tsx
  src/routes/SidebarRouter.tsx
  src/routes/WebRouter.tsx
Labels: 🐛 Bug, ✨ Feature, 🔗 API

#100 [✨ Feature] ocr 이미지 회전만 했을 경우 저장
  src/common/BankDropdown.tsx
  src/common/SideModal/SideModal.tsx
  src/pages/ADMIN/tax/components/AdminChartContent.tsx
  src/pages/ADMIN/tax/components/AdminTaxDetailModal.tsx
  src/pages/CS/TaxUpload/ImageCrop.tsx
  src/pages/CS/home/components/Refuse.tsx
  src/pages/CS/tax/EditTax.tsx
Labels: 🐛 Bug, 🔗 API

#102 [⚙️ Setting] Update Readme
  README.md
Labels: 📄 Docs
