Repository SEOULMILK-1/SEOULMILK1_FE, pull requests merged in 2025-02, with the labels that each got.

#3 chore: 폴더구조 설정
  .github/pull_request_template.md
  src/App.css
  src/assets/react.svg
  src/common/test.tsx
  src/hooks/test.tsx
  src/index.css
  src/pages/index.tsx
  src/pages/login/components/test.tsx
  src/pages/login/index.tsx
  src/pages/login/test.style.ts
  src/routes/router.tsx
  src/styles/designToken.css
  src/styles/globalStyle.ts
  src/styles/reset.css
  src/utils/test.tsx
Labels: ⚒️ Setting

#4 chore: ReadMe 수정
  README.md
Labels: 📄 Docs

#7 [⚙️ Setting] 디자인시스템 컬러팔레트 및 프리티어 설정 #6
  .prettierrc
  src/styles/designToken.css
Labels: 💄 Style

#13 [✨ Feature] 로그인 UI 구현
  .github/workflows/update-types.yml
  package-lock.json
  package.json
  public/Icon/LoginDeleteIcon.tsx
  public/Icon/RedLogoIcon.tsx
  public/Icon/ResetIcon.tsx
  public/Icon/SearchIcon.tsx
  public/Icon/WarningIcon.tsx
  public/vite.svg
  src/App.tsx
  src/common/Button.tsx
  src/common/test.tsx
  src/pages/CompoExample.tsx
  src/pages/index.ts
  src/pages/index.tsx
  src/pages/login/components/ErrorMessage.tsx
  src/pages/login/components/LabelInput.tsx
  src/pages/login/components/LoginFooter.tsx
  src/pages/login/components/test.tsx
  src/pages/login/index.tsx
  src/pages/login/test.style.ts
  src/routes/router.tsx
  src/styles/globalStyle.ts
  src/styles/reset.css
  tailwind.config.ts
Labels: ✨ Feature, 💄 Style

#18 [✨ Feature] 기간, 상태 컴포넌트 UI 구현
  public/Icon/LoginDeleteIcon.tsx
  public/Icon/StateDropdownIcon.tsx
  src/common/Button.tsx
  src/common/SelectMonth.tsx
  src/common/StateDropdown.tsx
  src/pages/CompoExample.tsx
Labels: 💄 Style
